name: kakeibo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.fl
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.2

environment:
  sdk: ">=3.1.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  sqflite:
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  google_fonts: 5.0.0
  flutter_slidable:
  json_annotation:
  freezed_annotation:
  liveroom:
  percent_indicator:
  go_router:
  pixel_color_image:
  web_socket_channel:
  scroll_to_index:
  # firebase_core:
  # firebase_analytics:
  # firebase_auth:
  # google_sign_in:
  device_preview_minus: # device_preview が開発停止中なので代わりに使う
  envied:
  shared_preferences:
  # cloud_firestore:
  intl:
  youtube_player_iframe:
  url_launcher:
  flutter_web_plugins:
    sdk: flutter
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.9
  modal_bottom_sheet: ^3.0.0-pre
  syncfusion_flutter_charts: ^25.1.35



  # The following adds the Cupertino Icons font to your application.  
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  freezed:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_generator:
  envied_generator:
  sqflite_common_ffi:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: sf_ui
      fonts:
        - asset: assets/fonts/sf-ui-display-ultralight.otf
          weight: 100
        - asset: assets/fonts/sf-ui-display-thin.otf
          weight: 200
        - asset: assets/fonts/sf-ui-display-light.otf
          weight: 300
        - asset: assets/fonts/sf-ui-display-regular.otf
          weight: 400
        - asset: assets/fonts/sf-ui-display-medium.otf
          weight: 500
        - asset: assets/fonts/sf-ui-display-semibold.otf
          weight: 600
        - asset: assets/fonts/sf-ui-display-bold.otf
          weight: 700
        - asset: assets/fonts/sf-ui-display-heavy.otf
          weight: 800
        - asset: assets/fonts/sf-ui-display-black.otf
          weight: 900

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  ios: true
  image_path: "assets/images/launcher_icon.png"
  remove_alpha_ios: true
  # android: true
  # adaptive_icon_background: "assets/images/launcher/icon_adaptive_background.png"
  # adaptive_icon_foreground: "assets/images/launcher/icon_adaptive_foreground.png"